<?php
$topic = $block->getData('topic');
if (!empty($topic)) {
    echo $topic;
}

	// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    // $customerSession = $objectManager->get('Magento\Customer\Model\Session');
	// $lastorderId = $customerSession->getLastOrderId();
	
 // $topic = $block->getData('topic');
// $block->getDescription(); 


	// $orderPrice = $block->getOrderPrice();
	// $orderTransId = $block->getTransId()

	 // $html =  "<p>try ".$topic."</p>";
	// $html .=  "<p>For your Reference, the following payment details are important for your records</p>";
	// $html .=  "<ol>";
	// $html .=  "<li>Your Mpesa reciept Number for your transaction is : ".$orderTransId.".</li>";
	// $html .=  "<li>The order ID : #".$orderID." has been generated successful </li>";
	// $html .=  "<li>Total rder amount of : KES ".$orderPrice." has been detected from your Mpesa</li>";
	// $html .=  "<li>Thank you for purchasing from us</li>";
	// $html .=  "</ol>";
	// $html .=  "<p>You will receive email notification from us shortly.</p>";
	 // echo $html;
	
?>